# Generated by Django 3.1.2 on 2020-10-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=7, verbose_name='Task No')),
                ('sub_task_no', models.CharField(max_length=50, null=True, verbose_name='Sub Task No')),
                ('task_value', models.IntegerField(max_length=5, null=True, verbose_name='Task Value')),
                ('category', models.CharField(choices=[('Category A', 'Category A'), ('Category B', 'Category B'), ('Category C', 'Category C')], max_length=50)),
            ],
        ),
    ]
