# Generated by Django 3.1.2 on 2020-10-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_value',
            field=models.IntegerField(null=True, verbose_name='Task Value'),
        ),
    ]
